name: ci on macos
on:
  push:
    branches:
      - mai

jobs:
  check_installable_on_macos:
    if: github.event.pull_request.draft == false
    runs-on: macOS-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@master
      - uses: actions/cache@v3
        with:
          key:
            ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.pytorch-version
            }}-${{ hashFiles('**/setup.py') }}-${{ hashFiles('**/Makefile') }}
          path: ~/.cache/pip
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - id: pr-labels
        name: Get PR labels
        uses: joerick/pr-labels-action@v1.0.9
      - env:
          CHAINER_VERSION: 6.0.0
          ESPNET_PYTHON_VERSION: ${{ matrix.python-version }}
          TH_VERSION: ${{ matrix.pytorch-version }}
          USE_CONDA: ${{ matrix.use-conda }}
          WITH_OMP: false
        name: install espnet
        run: "./ci/install_macos.sh

          "
      - id: measurement-6
        name: Record Measurement After install espnet
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: install espnet
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    strategy:
      matrix:
        python-version:
          - "3.10"
        pytorch-version:
          - 2.1.2
        use-conda:
          - true
          - false
