name: publish doc
on:
  push:
    branches:
      - mai

jobs:
  generate_and_deploy_doc:
    if:
      "github.event_name != 'pull_request' ||\n  (github.event.pull_request.draft\
      \ == false && needs.get_labels.outputs.is_doc == 'true')\n"
    needs: get_labels
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          key: pip-${{ hashFiles('**/setup.py') }}
          path: ~/.cache/pip
      - uses: actions/setup-python@v5
        with:
          architecture: x64
          python-version: "3.10"
      - name: check OS
        run: cat /etc/os-release
      - id: measurement-5
        name: Record Measurement After check OS
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: check OS
          task: get-measurement
      - name: install dependencies
        run: "sudo apt-get update -qq

          sudo apt-get install -qq -y cmake python3-dev git pandoc ffmpeg bc nodejs
          npm

          "
      - id: measurement-7
        name: Record Measurement After install dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: install dependencies
          task: get-measurement
      - env:
          CHAINER_VERSION: 6.0.0
          ESPNET_PYTHON_VERSION: 3.1
          TH_VERSION: 2.0.1
          USE_CONDA: false
        name: install espnet
        run: ./ci/install.sh
      - id: measurement-9
        name: Record Measurement After install espnet
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: install espnet
          task: get-measurement
      - name: generate doc
        run: ./ci/doc.sh
      - id: measurement-11
        name: Record Measurement After generate doc
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: generate doc
          task: get-measurement
      - if: github.ref == 'refs/heads/master'
        name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
  get_labels:
    outputs:
      is_doc: ${{ steps.check-labels.outputs.is_doc }}
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - id: pr-labels
        name: Get PR labels
        uses: joerick/pr-labels-action@v1.0.9
      - id: check-labels
        name: Check whether PR is related to documentation
        run:
          "if [ -n \"$GITHUB_PR_LABEL_DOCUMENTATION\" ]; then\n  echo \"is_doc=true\"\
          \ >> \"$GITHUB_OUTPUT\"\nelse\n  echo \"is_doc=false\" >> \"$GITHUB_OUTPUT\"\
          \nfi\n"
      - id: measurement-3
        name: Record Measurement After Check whether PR is related to documentation
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Check whether PR is related to documentation
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
